version: '3'

services:
  app:
    image: chb1828/scheduler:0.0.1
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - TZ=Asia/Seoul
    ports:
      - 8882:8882
    depends_on:
      - db
  db:
    image: postgres:9.6.1
    volumes:
      - db-data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=scheduler
      - POSTGRES_PASSWORD=chb
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
      - TZ=Asia/Seoul
    ports:
    - 5432:5432

volumes:
  db-data:
