version: 2.1

jobs:
  build_and_push_docker_image:
    machine: true
    steps:
      - checkout
      - run:
          name: build and push docker image
          command: |
            set -x
            REPO="https://github.com/chb1828/MyDiary-Server.git"
            chmod +x gradlew
            ./gradlew clean build
            DOCKER_USER=chb1828
            DOCKER_PASS=qjaand6378
            PRJ_NAME=scheduler
            PRJ_JAR=${PRJ_NAME}.jar
            LAST_GIT_TAG=$(git ls-remote --tags $REPO | awk '{print $2}' | grep -v '{}' | awk -F"/" '{print $3}' | sort -n -t. -k1,1 -k2,2 -k3,3 | tail -n 1)
            NEW_IMAGE="zechery/bitfront-price-alert:${LAST_GIT_TAG}"
            docker build -t ${PRJ_NAME} --build-arg JAR_FILE=build/libs/${PRJ_JAR} ./
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
            docker tag ${PRJ_NAME} ${DOCKER_USER}/${PRJ_NAME}:latest
            docker push ${DOCKER_USER}/${PRJ_NAME}

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build_and_push_docker_image:
          filters:
            branches:
              only: 01-travisCi-to-CircleCi